### ISSUE TITLE
"Forward" Google Geo Coder

### ISSUE THREAD

**Issue by ESmith92** [gios-asu/search-api#104]
so I read over how google set up the calls for the forward geo coding and it seems that the reverse geo coder classes could be use with a different parser and a update to the url builder to allow for address parameter rather than lat and log.

Would you like to have the two types of geo coders completely separate or should the forward geo coder only have a new parser and maybe a new url builder?

**Comment by rraub** [comment]
What is common between the two should be shared and what is different should be different. What I shouldn't see is two classes that are 90% the same with the exception of the word "forward" or "reverse". Does that make sense? 

Two parsers could be fine, if they have the same interface then I would make them inherit or implement that interface to reduce code duplication.

**Comment by ESmith92** [comment]
alright, should i have the url be one class then... the only difference is  address= rather than latlng= in the url
