### ISSUE TITLE
Types of Searches

### ISSUE THREAD

**Issue by jkarner** [gios-asu/search-api#12]
http://www.gliffy.com/go/publish/image/9208865/L.png

We know that we'll probably need more methods in the concrete strategies in order to fully implement the strategy. In the meantime, we were wondering how the SearchEngine will connect to the Services? Is it a dependency to the interface?

**Comment by idmontie** [comment]
Did we resolve this issue in our last couple of meetings? The question is a bit outdated with respect to the system architecture that was decided upon.

Feel free to reopen this if it is still relevant.
