### ISSUE TITLE
No matchers found for beEmpty and beGreaterThan.

### ISSUE THREAD

**Issue by kenprice** [gios-asu/search-api#16]
Couple of the tests were broken.

```
SearchApi/SearchEngine                                                  
  26  - it should return non empty results
      no beEmpty([array:0]) matcher found for [array:2].

SearchApi/SearchEngine                                                  
  33  - it should return multiple results
      no beGreaterThan([array:1]) matcher found for [integer:2].
```

The `phpspec/phpspec` version in my `vendor` directory is 2.0.x-dev. I had also tried 2.2.x-dev (which is what gets installed when doing `composer install ...` just like in the readme).

Adding inline matchers for these had fixed it.

```
  public function getMatchers()
  {
    return [
      'beGreaterThan' => function ( $subject, $number ) {
        return $subject > $number;
      },
      'beEmpty' => function ( $subject ) {
        return empty( $subject );
      }];
  }
```

I thought it might be an issue with the phpspec version. I made a PR and watched TravisCI run the tests and have the same error. I also thought I was missing some phpspec extension. And of course, I could've done something completely wrong.

Am I going about this wrong?
https://github.com/gios-asu/search-api/compare/kenp-initial
Should my code above cause these errors to happen? Are the inline matchers I have above have the correct logic?

**Comment by rraub** [comment]
That is my mistake, I didn't realize I was using matchers that weren't defined. I was expecting the specs to fail, just not like that :wink: 
Instead of trying to define our own matchers we should try and use an extension like this one https://github.com/bravesheep/phpspec-extra-matchers 

Not that defining our own matchers is the worst thing in the world, its just time consuming.

**Comment by idmontie** [comment]
We should just write better spec tests rather than these washy ones. They were a good start, but I rewrote them in my branch.
