### ISSUE TITLE
Query builder for SolrSearch?

### ISSUE THREAD

**Issue by kenprice** [gios-asu/search-api#24]
I thought it might be useful to have a `QueryBuilder` interface, with a method that takes the search terms and search options and returns a query string for SOLR. That will move the responsibility of building a query out of `SolrSearch` so that `SolrSearch` can focus on making the query, parsing the results, and returning the results as `SearchResult`.

WIP of diagram here.
http://www.gliffy.com/go/publish/image/9344405/L.png

`QueryBuilder` will live in its own namespace. Something like `SearchApi\Providers\SolrQueryBuilder`. Within specific implementations of `QueryBuilder`, we can implement our own search strategies to try to get the most relevant results back. SOLR supports powerful query parameters, and there are a lot of them. So I thought it would be useful to separate query building from making the actual query request / parsing query response.

Would this be useful to you @idmontie @rraub ?

**Comment by rraub** [comment]
The separation of query construction and execution does make sense, I think that would be a good way to split it up. :+1:

**Comment by idmontie** [comment]
:+1: The namespace should probably be `SearchApi\Builders` though.

**Comment by kenprice** [comment]
@idmontie I think you're right. When I thought about this I had Solr specifically in mind. I'll go ahead and use the namespace `SearchApi\Builders` instead.
