### ISSUE TITLE
Synonyms - during query or indexing?

### ISSUE THREAD

**Issue by kenprice** [gios-asu/search-api#32]
Right now might be too early to make an issue of this. But after reading about SOLR schemas, it made me think - should synonym filtering occur during indexing or querying? SOLR docs says it should be during indexing, but I'm not sure how extensible this is.

Just going to leave these here for now.
- [Query-time multi-word synonym expansion](https://issues.apache.org/jira/browse/SOLR-4381)
- [Better synonym handling in SOLR](http://nolanlawson.com/2012/10/31/better-synonym-handling-in-solr/)

**Comment by rraub** [comment]
This is a topic for debate, I think we'll find the answer is going to be a little of both given they each have their pros and cons. One factor that will dictate where and how much we do synonym handling is performance.

**Comment by rraub** [comment]
index time
