### ISSUE TITLE
Basic SOLR schema

### ISSUE THREAD

**Issue by kenprice** [gios-asu/search-api#33]
It would be helpful for me to have a basic SOLR schema for working on my query builder and making a mock SOLR server response. I could even set up my own SOLR server to play with. Here's what I came up with so far for my `schema.xml`

[gist](https://gist.github.com/kenprice/82ce5ae16e9a09cb81f0)

```
<?xml version="1.0" encoding="UTF-8" ?>

<schema name="gios-asu" version="0.1">

  <fields>
    <!-- Should id be string? -->
    <field name="id" type="string" indexed="true" stored="true" required="true"/>

    <field name="title" type="textgen" indexed="true" stored="true"/>

    <!-- textgen tokenizes at whilespace, will catenate words and split on case change when
          indexed and queried. So a query for "Augustus DeMorgan" and "Augustus De-Morgan" 
          will both be a match for Augustus De Morgan
    -->
    <field name="author" type="textgen" indexed="true" stored="true"/>
    <field name="author_last_name" type="textgen" indexed="true" stored="true"/>
    <field name="author_first_name" type="textgen" indexed="true" stored="true"/>

    <field name="organization" type="textgen" indexed="true" stored="true"/>

    <field name="publish_date" type="TrieDateField" indexed="true" stored="true"/>

    <!-- document body should use a special type of class solr.TextField so analyzers can
       be used -->
    <field name="body" type="document_body" indexed="true" stored="true"/>

    <!-- collection of all fields; not stored. may be useful for querying -->
    <field name="collector" type="textgen" indexed="true" stored="false" multiValued="true"/>
  </fields>

  <!-- may simplify some queries to combine fields into one -->
  <copyField source="title"           dest="collector"/>
  <copyField source="author"          dest="collector"/>
  <copyField source="body"            dest="collector"/>
  <copyField source="organization"    dest="collector"/>

  <!-- custom type for document body -->
  <fieldType name="document_body" class="solr.TextField">
    <analyzer type="index">
      <!-- sample; Tokenization and filtering can happen during indexing
      <tokenizer class="solr.StandardTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
      <filter class="solr.KeepWordFilterFactory" words="keepwords.txt"/>
      <filter class="solr.SynonymFilterFactory" synonyms="syns.txt"/>
      -->
    </analyzer>
    <analyzer type="query">
      <!-- sample; Tokenization and filtering can happen during querying
      <tokenizer class="solr.StandardTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
      -->
    </analyzer>
  </fieldType>
</schema>
```

@rraub @idmontie please give me some feedback. I'm most concerned right now about names and types of fields. Also, what other fields would you need? Thanks!

**Comment by rraub** [comment]
I'm glad your to the point where you need to ask this question! I've had a rough schema in mind, so here are the main differences and notes to incorporate into yours:
- There are more times than just the published_date, a paper could have a study period of several years and that is valuable information to search on in addition to the publication date. The boring term we use for this type of thing is "temporal coverage" which might work well as a `datetimerange` and also `multivalue`'d.
- What about locations? Ideally we should be storing their point and textual form. Solr 4+ gives us the `LatLonType` to use. Again `multivalue`'d.
- There can and usually is multiple authors. 
- We will also need to store a url or url path to the item, otherwise we would have to maintain some logic for how to figure out to link to each item.
- Concatenating everything together into a single field is also a good move, that will be useful.

**Comment by kenprice** [comment]
I'm having a hard time thinking about how to represent temporal coverage. I think it'd be important to have a description associated with date-ranges. But SOLR does not support struct-like field types. I could do a multiValued field or a straight string field (will need to be parsed to obtain daterange + description) to achieve this. Of course, I could skip the description and just store dates, but I'm not certain that would be useful. For the purpose of this project, would you want an associated description with date-ranges?

Location: I'm thinking either two separate fields, `locations_coord` and `location_name` (both multiValued) OR a single `locations` field with text, with lat-long and names in text (multiValued of course). The latter has an advantage of having a single field for location, but has the disadvantage of having to parse the field's contents to see if it's a name or lat/long. What would you prefer?

**Comment by rraub** [comment]
What would the temporal coverage description say? "publication date"? are you thinking to use it to qualify what the date means to this item? 

Lets say we have a paper thats published in Jan 2015, and the paper is about rainfall from Jan 2000 - Jan 2010. I was imagining this paper would just have two temporal coverages, (Jan 2015, and Jan 2000 - Jan 2010). It's rather hard to pull out a textual context for dates from sentences, which is why I don't think   storing a description would be that useful. 

For Locations, I would have both fields. Some times we'll have lat/lon's other times we just might have location names.

**Comment by kenprice** [comment]
I'd make publication date its own field, since this is a field in common with any research paper. This would be a single date and not a range, so I could use the `TrieDateField` type.

It might not always be possible to get any useful date ranges from a paper when ingesting them. So that was my reasoning behind having a separate field for 'other' temporal coverage. I agree that it would be hard to get a meaningful description for these date ranges when ingesting a large number of papers (someone will have to do this manually, or use some NLP black magic), so I'll skip the 'descriptions' part.

Here's a revised `schema.xml`.
[gist](https://gist.github.com/kenprice/fe16f5f77f9910d5ec65)

```
<?xml version="1.0" encoding="UTF-8" ?>

<schema name="gios-asu" version="0.1">

  <fields>
    <!-- Should id be string? -->
    <field name="id" type="string" indexed="true" stored="true" required="true"/>

    <field name="title" type="textgen" indexed="true" stored="true"/>

    <!-- ATTRIBUTION -->
    <!-- textgen tokenizes at whilespace, will catenate words and split on case change when
          indexed and queried. So a query for "Augustus DeMorgan" and "Augustus De-Morgan" 
          will both be a match for Augustus De Morgan
    -->
    <field name="authors" type="textgen" indexed="true" stored="true" multiValued="true"/>
    <field name="contributors" type="textgen" indexed="true" stored="true" multiValued="true"/>
    <field name="organizations" type="textgen" indexed="true" stored="true" multiValued="true"/>

    <!-- SPATIAL AND TEMPORAL COVERAGE -->
    <field name="dates" type="temporal_coverage" indexed="true" stored="true" multiValued="true"/>
    <field name="locations" type="location " indexed="true" stored="true" multiValued="true"/>
    <dynamicField name="*_coordinate"  type="tdouble" indexed="true"  stored="false"/>
    <field name="location_names" type="textgen " indexed="true" stored="true" multiValued="true"/>

    <!-- document body should use a special type of class solr.TextField so analyzers can
       be used -->
    <field name="body" type="document_body" indexed="true" stored="true"/>

    <field name="publication_date" type="TrieDateField" indexed="true" stored="true"/>

    <!-- collection of all fields; not stored. may be useful for querying -->
    <field name="collector" type="textgen" indexed="true" stored="false" multiValued="true"/>
  </fields>

  <!-- may simplify some queries to combine fields into one -->
  <copyField source="title"               dest="collector"/>
  <copyField source="authors"             dest="collector"/>
  <copyField source="contributors"        dest="collector"/>
  <copyField source="organizations"       dest="collector"/>
  <copyField source="body"                dest="collector"/>
  <copyField source="organization"        dest="collector"/>
  <copyField source="location_names"    dest="collector"/>

  <!-- SPATIAL AND TEMPORAL COVERAGE -->
  <fieldType name="temporal_coverage" class="solr.DateRangeField">
  <fieldType name="location" class="solr.LatLonType" subFieldSuffix="_coordinate"/>

  <!-- custom type for document body -->
  <fieldType name="document_body" class="solr.TextField">
    <analyzer type="index">
      <!-- sample; Tokenization and filtering can happen during indexing
      <tokenizer class="solr.StandardTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
      <filter class="solr.KeepWordFilterFactory" words="keepwords.txt"/>
      <filter class="solr.SynonymFilterFactory" synonyms="syns.txt"/>
      -->
    </analyzer>
    <analyzer type="query">
      <!-- sample; Tokenization and filtering can happen during querying
      <tokenizer class="solr.StandardTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
      -->
    </analyzer>
  </fieldType>
</schema>
```

**Comment by rraub** [comment]
Looks Good!
