### ISSUE TITLE
Test Data Workflow Design

### ISSUE THREAD

**Issue by jkarner** [gios-asu/search-api#36]
We need to have a pipeline diagram of test data to flow through the system and what we expect to get and return at each state

**Comment by jkarner** [comment]
@rraub 
branch jillian-feature-testworkflow addresses this initially but it's not complete, we have a bit too much static data right now
Needs
- fix to spec test
- pass coding standards (which won't run and check for me)

**Comment by rraub** [comment]
FYI Travis will run the coding standards for you when you push your branch to github. https://travis-ci.org/gios-asu/search-api/jobs/94676722

**Comment by kenprice** [comment]
@jkarner Not sure what you mean by pipeline diagram, but I made a sequence diagram for the whole system and `SolrSearch` [here](https://github.com/gios-asu/search-api/wiki/Model-for-dynamic-aspects-of-the-project).

**Comment by rraub** [comment]
if @jkarner agrees, we can close this issue since @kenprice made a sequence diagram that shows how the different parts of this system work together through the search engine and the integration tests in #79
