### ISSUE TITLE
Error Exception when running spec tests

### ISSUE THREAD

**Issue by iajohns1** [gios-asu/search-api#39]
I've had this problem since the beginning, but I'd like to remove it. Have any ideas?
This appears bellow every spec test result (pass or fail)

```
[PhpSpec\Exception\Example\ErrorException]
warning: file_put_contents(coverage/phpspec.cov): failed to open stream: No such file or di
rectory in /home/ian/Desktop/search-api/vendor/phpunit/php-code-coverage/src/CodeCoverage/R
eport/PHP.php line 45
```

**Comment by kenprice** [comment]
Check the directory `/home/ian/Desktop/search-api/vendor/phpunit/php-code-coverage/src/CodeCoverage/R
eport/`
You might be missing something in the `vendor` directory. If so you'll need to do `composer install` again.

**Comment by kenprice** [comment]
Also if you want to run the same tests TravisCI is doing, you'll need to do:

```
vendor/bin/phpunit # --coverage-clover /tmp/coverage/clover.xml
vendor/bin/phpspec run -c .phpspec.yml 
vendor/bin/phpcs --standard=GIOS --ignore= ./src ./test
```

You can save it as a script in the project root directory, but don't commit it!

**Comment by rraub** [comment]
Try making a `coverage` directory in your working copy to see if it fixes it.
