### ISSUE TITLE
File Upload (Not a Real Issue)

### ISSUE THREAD

**Issue by idmontie** [gios-asu/search-api#4]
The GitHub wiki does not allow file uploads to it, so if you ever want to host a file and link to it from the wiki, the "normal" procedure is to have someone on the team make a "File Upload" issue like I am doing now.

The issue will be closed, but if you ever want to share a file (GitHub supports a few image types), just drag and drop the file into a comment response here.

PS: You can ping someone on GitHub (and GitHub will email them if they have email notification turned on), by using the following syntax: @idmontie.

**Comment by idmontie** [comment]
![gios-tagger-01](https://cloud.githubusercontent.com/assets/412382/10029282/e26cb772-6125-11e5-846d-1859059b4420.jpg)
![gios-tagger-02](https://cloud.githubusercontent.com/assets/412382/10029285/e2702394-6125-11e5-81a4-ec90bac1ebda.jpg)
![gios-tagger-03](https://cloud.githubusercontent.com/assets/412382/10029287/e271378e-6125-11e5-9cf9-ea2ccf4d0f3a.jpg)
![gios-tagger-04](https://cloud.githubusercontent.com/assets/412382/10029283/e26ed340-6125-11e5-9b25-bd1ffd79876e.jpg)
![gios-tagger-05](https://cloud.githubusercontent.com/assets/412382/10029284/e2700d3c-6125-11e5-9217-229843b95330.jpg)
![gios-tagger-06](https://cloud.githubusercontent.com/assets/412382/10029286/e270c416-6125-11e5-9987-7263b3dbb3af.jpg)
![gios-tagger-07](https://cloud.githubusercontent.com/assets/412382/10029292/e28a3e3c-6125-11e5-90a9-e4c14dd0ec1a.jpg)
![gios-tagger-08](https://cloud.githubusercontent.com/assets/412382/10029289/e2862284-6125-11e5-8c5e-4c9a3223bd30.jpg)
![gios-tagger-09](https://cloud.githubusercontent.com/assets/412382/10029290/e2860402-6125-11e5-84c9-5437e8e67d64.jpg)
![gios-tagger-10](https://cloud.githubusercontent.com/assets/412382/10029291/e288b9c2-6125-11e5-9f4f-59091465b3ff.jpg)
![gios-tagger-11](https://cloud.githubusercontent.com/assets/412382/10029288/e2860f88-6125-11e5-8b4b-efaeef6932f8.jpg)

**Comment by rraub** [comment]
![designpatternrelationships](https://cloud.githubusercontent.com/assets/295804/10431641/0cfee04c-70bb-11e5-8529-40043b2a911b.png)

**Comment by ESmith92** [comment]
![20151020_143152](https://cloud.githubusercontent.com/assets/14352987/10622739/393ee254-773e-11e5-87ab-f98a93d54e76.jpg)
