### ISSUE TITLE
Configuration utility

### ISSUE THREAD

**Issue by idmontie** [gios-asu/search-api#41]
It's built into Nectary: https://github.com/gios-asu/nectary/blob/develop/src/configuration/configuration.php

**Comment by rraub** [comment]
examples

```
    Configuration::get_instance()->set( 'static_asset_path', 'https://static.sustainability.asu.edu' ); // with default
    Configuration::get_instance()->get( 'static_asset_path', 'https://static.sustainability.asu.edu' ); // with another default
    Configuration::get_instance()->get( 'static_asset_path'); // with no default
```

Also look at https://github.com/gios-asu/nectary/blob/develop/tests/unit/configuration-utilities-test.php

you can use the global function `config()` that nectary provides.
