### ISSUE TITLE
Create Digital Ocean Server for SOLR

### ISSUE THREAD

**Issue by jkarner** [gios-asu/search-api#47]

**Comment by rraub** [comment]
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=digital%20ocean%20pagefile

**Comment by jkarner** [comment]
[solr site](http://jilliantessa.me:8983/solr/#/)
[server setup guide](https://github.com/gios-asu/search-api/wiki/Server-Setup)

**Comment by rraub** [comment]
:+1:
