### ISSUE TITLE
Schedule a meeting time for Spring 2016

### ISSUE THREAD

**Issue by rraub** [gios-asu/search-api#48]
I've created a doodle poll for everyone to fill out to see when we are all available.

http://doodle.com/poll/nk72cf9wrca9cnv5

**Comment by rraub** [comment]
@jkarner @trojchanakasetchai @kenprice @ESmith92 @iajohns1

**Comment by jkarner** [comment]
All of our team has submitted our availability on the Doodle

**Comment by rraub** [comment]
Tuesday at 2:00pm seemed to be the closest time that we could all meet.  Would something like 2:30-3:30 work for everyone?

**Comment by kenprice** [comment]
:+1: for 2:30-3:30
or 2:00-3:00 (don't care which)

**Comment by ESmith92** [comment]
I have a class at 3, so if it is fine that I leave half way through then I'm good with it. ..

Probably would not be for the best though

**Comment by iajohns1** [comment]
My last class for the day gets out at 1:15pm.
I would prefer not to waste more than an hour before the meeting.
I would be OK with 2:00pm, but 2:30pm is pushing it for me.

**Comment by rraub** [comment]
@trojchanakasetchai care to weigh in?

**Comment by trojchanakasetchai** [comment]
I recommend doing 1:30pm to 2:30pm on Tuesday if possible and 2pm-3pm otherwise. There is no way to choose a time that all 5 are free with my current schedule, but I will change my classes to try to make a 1:30 or 2pm meeting on Tuesday.

**Comment by rraub** [comment]
would 1:30 - 2:30 Tuesday work for everyone? 

@kenprice @iajohns1

**Comment by iajohns1** [comment]
Yes, that time is perfect for me.

**Comment by ESmith92** [comment]
Works for me

**Comment by jkarner** [comment]
Works for me

**Comment by kenprice** [comment]
:+1: for 1:30 - 2:30

**Comment by rraub** [comment]
Alright 1:30-2:30 Tuesday it is, I'll book the room. See you all then!
