### ISSUE TITLE
Setup automated testing scaffolding

### ISSUE THREAD

**Issue by rraub** [gios-asu/search-api#5]
This will include [phpunit](https://phpunit.de/) and [phpspec](http://www.phpspec.net/) that will be run on travis-ci.

**Comment by idmontie** [comment]
You will also need to merge the coveralls results between both phpunit and phpspec.

No idea how to do that yet, I have the same issue in the `sustainability-game` repo.

**Comment by rraub** [comment]
You can use [phpcov](https://github.com/sebastianbergmann/phpcov) to merge two code coverage reports that are in the php format. See: https://stackoverflow.com/questions/11783854/phpspec-and-coverage-report
