### ISSUE TITLE
create a current design document on the wiki

### ISSUE THREAD

**Issue by rraub** [gios-asu/search-api#55]

**Comment by rraub** [comment]
This is our starting point: https://github.com/gios-asu/search-api/wiki/documentation but we've made some changes to this already

**Comment by kenprice** [comment]
Interpreted issue to mean: Create new class diagram to reflect our current design.

Updated [documentation](https://github.com/gios-asu/search-api/wiki/documentation) with new class diagram, where we had left off at the end of last semester.

Tagged "In Progress" until further feedback from @rraub

**Comment by rraub** [comment]
:+1:  looks good, thanks @kenprice
