### ISSUE TITLE
Provide SSH Public keys to access DO server with SOLR

### ISSUE THREAD

**Issue by jkarner** [gios-asu/search-api#56]
Ken and Tom are working on the SOLR configuration and implementation and I will create accounts for them once public keys are provided.

In Linux/Unix Environments provide the .pub file generated from this command
`ssh-keygen -t rsa -b 4096`

@kenprice @trojchanakasetchai

**Comment by rraub** [comment]
still waiting to verify with @trojchanakasetchai

**Comment by jkarner** [comment]
@trojchanakasetchai and @kenprice can login and work on the DO instance
