### ISSUE TITLE
NER tagger dependencies

### ISSUE THREAD

**Issue by kenprice** [gios-asu/search-api#62]
TODO for the NER tagger dependency
- Create a symbolic link to the `.tagger` and `.jar` file, store at `/usr/local/bin`
- Have Travis download the dependencies and symlink

**Comment by idmontie** [comment]
Here is an example from another we repo we have that requires binary dependency: https://github.com/gios-asu/pdf-generation-experiment/blob/master/index.php

```
$snappy = new Pdf('/usr/local/bin/wkhtmltopdf');
```

We then have instructions in our README file:

```
1.  Download the binary: http://wkhtmltopdf.org/downloads.html
2.  Put it in `/usr/local/bin`
```

**Comment by rraub** [comment]
or we could create a vendor folder and put the jar's we need in there.

**Comment by rraub** [comment]
Just dont call it `vendor` because composer uses that folder already

**Comment by kenprice** [comment]
I helped out a bit. Created a branch off `ian-devel`, and made the following changes:
- Used configuration utility to make root path to Stanford NER library configurable.
- Travis: Fetch Stanford NER library and cache it. Save it to `./lib` wrt project path.
- Travis: Use Java 8 OpenJDK instead of default Java 7. Used `linuxbrew` to achieve this.
- Travis: Cache `~/.linuxbrew` so we don't have to keep downloading `linuxbrew`.
- Travis: Produce a `config.conf` file. The config file produced in Travis tests mainly concerns the NER tagger at this point. The `SolrApiUrl` entry is a placeholder.

The goal of these changes was to configure Travis properly so that Stanford NER can run on it.

If @rraub or @idmontie wants to review my changes, you can find it [here](https://github.com/gios-asu/search-api/compare/ken-ner-travis?expand=1).

I went ahead and merged my change into `ian-devel` after coordinating with @iajohns1
