### ISSUE TITLE
snake_case

### ISSUE THREAD

**Issue by kenprice** [gios-asu/search-api#68]
Are we using snake_case??

Latest Travis build for my `ken-query-builder` branch is littered with these types of errors in the logs:

```
 18 | ERROR   | [ ] Variable "keywordStrings" is not in valid

    |         |     snake_case format

 18 | ERROR   | [ ] Variable "keywordStrings" is not in valid

    |         |     snake_case format

 21 | ERROR   | [ ] Variable "keywordStrings" is not in valid

    |         |     snake_case format
```

**Comment by idmontie** [comment]
The coding standards repo that we use was updated and now enforces the use of snake case. We are debating whether to disable it or not.

**Comment by rraub** [comment]
It can disabled with:
`<exclude name="WordPress.NamingConventions.ValidVariableName"/>`

But it might be worth keeping on if there aren't too many offenses to fix.

**Comment by rraub** [comment]
fixing these new coding standards should get in the way of a new features. Adopting a new standard thats requires big changes can be its own issue to be solved.

**Comment by kenprice** [comment]
Addressed in [this PR](https://github.com/gios-asu/search-api/pull/87); closing.
