### ISSUE TITLE
Search Request validation 

### ISSUE THREAD

**Issue by rraub** [gios-asu/search-api#71]
Where should the request get validated?

**Comment by rraub** [comment]
Lets make a sequence diagram!

**Comment by kenprice** [comment]
An idea for validating user input: Since `SearchRequest` contains all of the user input, we could have a `SearchRequestBuilder` which will be in charge of validating user input, and either return a `SearchRequest` object or an error.

**Comment by kenprice** [comment]
@rraub As for the sequence diagram, I made a diagram [here](https://github.com/gios-asu/search-api/wiki/Model-for-dynamic-aspects-of-the-project). I'm just learning UML, so it's basic. But I think I put enough information in the models I made.

**Comment by rraub** [comment]
@kenprice looks good, these diagrams illustrate nicely the basic flow of the application. One of the nice features of these diagrams is the discussions they can bring out: For example when should the execution not follow this exact path? (validation errors)
