### ISSUE TITLE
Capstone Class Assigned Wiki

### ISSUE THREAD

**Issue by jkarner** [gios-asu/search-api#8]
We are required to submit a wiki for our final portion this semester through the Blackboard wiki module.  Is there any problem with copying over the pages we create here to submit to our professor, or do they need to be reviewed and edited first?

**Comment by rraub** [comment]
I think the github wiki in this repo should work for your team, it would be nice to have everything in one place. Feel free to add/edit away!

**Comment by rraub** [comment]
Sorry just re-read your question; copying over the pages at submission time isn't ideal but I would hope that the convenience of having one wiki while the project is being developed will be worth the copy/paste work at submission time. I don't have a problem with it, everything in this repo is publicly viewable.

**Comment by jkarner** [comment]
If it's publicly view able, then I will check if I can just link this wiki to our professor through ours for grading. Otherwise, we will copy/past the work we do here into the Blackboard module for submission.
