### ISSUE TITLE
Make NerTagger Constructor, which is injectable

### ISSUE THREAD

**Issue by rraub** [gios-asu/search-api#85]
https://github.com/gios-asu/search-api/blob/develop/src/providers/ner-tagger.php#L31-L41

**Comment by iajohns1** [comment]
https://github.com/gios-asu/search-api/commit/39d1b1c93a5456d0322e78bb257a417ac0929f04

Is this what you wanted?
If so, you I create a pull request for this now or wait until I add error handling to the tagger?

**Comment by rraub** [comment]
That will work, after the construction of the NerTagger object we can mock the $tagger class variable for testing.
