### ISSUE TITLE
refactor geocoder into more generic pieces 

### ISSUE THREAD

**Issue by rraub** [gios-asu/search-api#94]
This would allow for more geocoders to be written in the future and keep all the google specific stuff isolated from any other geocoder implementations.

**Comment by rraub** [comment]
Was this issue completely addressed in #96 ?

**Comment by ESmith92** [comment]
In the sense that the Google geocoder is its own classes again, yes.

The only generic piece is the job decoder. Everything else is Google specific

**Comment by ESmith92** [comment]
In the sense that the Google geocoder is its own classes again, yes.

The only generic piece is the joson decoder. Everything else is Google specific

**Comment by ESmith92** [comment]
In the sense that the Google geocoder is its own classes again, yes.

The only generic piece is the json decoder. Everything else is Google specific

**Comment by ESmith92** [comment]
Phone is causing problems with a simple reply
